### ISSUE TITLE
test requests migration

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-rdm-migrator#88]
Assuming the communities cache exists, it only requires running the `requests` stream:

```yaml
data_dir: /root/zenodo-rdm/data
tmp_dir: /root/zenodo-rdm/tmp
cache_dir: /root/zenodo-rdm/cache
log_dir: /root/zenodo-rdm/logs/requests
db_uri: postgresql://user:pass@hostname:port/database
requests:
  extract:
    filepath: /root/zenodo-rdm/dumps/requests.jsonl
```
